### ISSUE TITLE
Failed to build service credential

### ISSUE THREAD

**Issue by sageata** [bridgefy/bridgefy_flutter#16]
I have attempted to build run the example code and followed the instructions.
Managed to make it work on iOS, however on Android I get the error: Failed to build service credential.

I have replaced all instances of 'me.bridgefy.android.sample' with my own application id 'com.example.crew_pda'

<img width="316" alt="image" src="https://github.com/bridgefy/bridgefy_flutter/assets/26434396/360c1f1f-e4b5-450a-9de9-6f264ded41a8">

Again, on iOS it works, but not on Android.

**Comment by julian-bridgefy** [comment]
@sageata  a new version is available that fixes the validation error and some improvements.
