### ISSUE TITLE
Is this package ready for Flutter 3?

### ISSUE THREAD

**Issue by marcotrumpet** [bridgefy/bridgefy_flutter#28]
Hi I'm trying to test this package but I have issues with Android.
First of all documentation lacks on infos about AndroidManifest like ```<meta-data
            android:name="com.bridgefy.sdk.API_KEY"
            android:value="API-KEY" />``` . I'm also receiving errors when calling the initialize method on android phone
`I/Process (23721): 	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:52)
I/Process (23721): 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
I/Process (23721): 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:231)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
I/Process (23721): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
I/Process (23721): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
I/Process (23721): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
I/Process (23721): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
I/Process (23721): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
I/Process (23721): Sending signal. PID: 23721 SIG: 9`

**Comment by marcotrumpet** [comment]
this happens on another android device 
`I/Process (23721): 	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:52)
I/Process (23721): 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
I/Process (23721): 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:231)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
I/Process (23721): 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
I/Process (23721): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
I/Process (23721): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
I/Process (23721): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
I/Process (23721): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
I/Process (23721): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
I/Process (23721): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
I/Process (23721): Sending signal. PID: 23721 SIG: 9`

**Comment by marcotrumpet** [comment]
@julian-bridgefy @rafaelcr @kekoyde @ghbfy hey, anyone is following development?

**Comment by mike-bridgefy** [comment]
Hello @marcotrumpet, thank you very much for the report, we apologize for the inconvenience caused to you.
We tested and found an issue in our SDK that affects Flutter. We already have the change ready but we are in the final tests, we will release a new version of the SDK and the Flutter plugin as soon as possible.

**Comment by marcotrumpet** [comment]
> Hello @marcotrumpet, thank you very much for the report, we apologize for the inconvenience caused to you. We tested and found an issue in our SDK that affects Flutter. We already have the change ready but we are in the final tests, we will release a new version of the SDK and the Flutter plugin as soon as possible.

hey thanks for the answer.. feel free to close this when the new version is published
