### ISSUE TITLE
1.1.2 doesn't work

### ISSUE THREAD

**Issue by marcotrumpet** [bridgefy/bridgefy_flutter#30]
Hey guys, also the new update doesn't work.. To make it start I had to add this into app gradle dependecies
`
    def lifecycle_version = "2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
` 

But event after this the app crashes with

> E/AndroidRuntime(28607): FATAL EXCEPTION: main
> E/AndroidRuntime(28607): Process: com.example.bridgefy_test, PID: 28607
> E/AndroidRuntime(28607): java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/logging/HttpLoggingInterceptor$Level;
> E/AndroidRuntime(28607): 	at me.bridgefy.network.di.NetworkRepositoryModule.<init>(Unknown Source:8)
> E/AndroidRuntime(28607): 	at me.bridgefy.di.DaggerBridgefyComponent$Builder.build(SourceFile:18)
> E/AndroidRuntime(28607): 	at me.bridgefy.di.Injector.init$bridgefy_release(SourceFile:5)
> E/AndroidRuntime(28607): 	at me.bridgefy.Bridgefy.init(SourceFile:2)
> E/AndroidRuntime(28607): 	at me.bridgefy.plugin.flutter.BridgefyPlugin.initialize(BridgefyPlugin.kt:60)
> E/AndroidRuntime(28607): 	at me.bridgefy.plugin.flutter.BridgefyPlugin.onMethodCall(BridgefyPlugin.kt:37)
> E/AndroidRuntime(28607): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/AndroidRuntime(28607): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/AndroidRuntime(28607): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/AndroidRuntime(28607): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/AndroidRuntime(28607): 	at android.os.Handler.handleCallback(Handler.java:942)
> E/AndroidRuntime(28607): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(28607): 	at android.os.Looper.loopOnce(Looper.java:211)
> E/AndroidRuntime(28607): 	at android.os.Looper.loop(Looper.java:300)
> E/AndroidRuntime(28607): 	at android.app.ActivityThread.main(ActivityThread.java:8294)
> E/AndroidRuntime(28607): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(28607): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> E/AndroidRuntime(28607): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
> E/AndroidRuntime(28607): Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.logging.HttpLoggingInterceptor$Level" on path: DexPathList[[zip file "/data/app/~~AeEnNIpGEIRU9UG6awe4jw==/com.example.bridgefy_test-vRkeL-aVOYg_K4oXTemgaA==/base.apk"],nativeLibraryDirectories=[/data/app/~~AeEnNIpGEIRU9UG6awe4jw==/com.example.bridgefy_test-vRkeL-aVOYg_K4oXTemgaA==/lib/arm64, /data/app/~~AeEnNIpGEIRU9UG6awe4jw==/com.example.bridgefy_test-vRkeL-aVOYg_K4oXTemgaA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
> E/AndroidRuntime(28607): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
> E/AndroidRuntime(28607): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> E/AndroidRuntime(28607): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> E/AndroidRuntime(28607): 	... 18 more
> W/e.bridgefy_test(28607): type=1400 audit(0.0:213040): avc: denied { search } for name="miuilog" dev="dm-50" ino=31304 scontext=u:r:untrusted_app:s0:c67,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.bridgefy_test
> W/e.bridgefy_test(28607): type=1400 audit(0.0:213041): avc: denied { search } for name="miuilog" dev="dm-50" ino=31304 scontext=u:r:untrusted_app:s0:c67,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.bridgefy_test
> W/e.bridgefy_test(28607): type=1400 audit(0.0:213042): avc: denied { search } for name="miuilog" dev="dm-50" ino=31304 scontext=u:r:untrusted_app:s0:c67,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.bridgefy_test
> W/e.bridgefy_test(28607): type=1400 audit(0.0:213043): avc: denied { search } for name="miuilog" dev="dm-50" ino=31304 scontext=u:r:untrusted_app:s0:c67,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.bridgefy_test
> W/e.bridgefy_test(28607): type=1400 audit(0.0:213044): avc: denied { search } for name="miuilog" dev="dm-50" ino=31304 scontext=u:r:untrusted_app:s0:c67,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.bridgefy_test
> W/OOMEventManagerFK(28607): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
> I/Process (28607): Process is going to kill itself!
> I/Process (28607): java.lang.Exception
> I/Process (28607): 	at android.os.Process.killProcess(Process.java:1330)
> I/Process (28607): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:202)
> I/Process (28607): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
> I/Process (28607): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
> I/Process (28607): 	at io.flutter.embedding.engine.dart.DartMessenger.handleError(DartMessenger.java:419)
> I/Process (28607): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:300)
> I/Process (28607): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> I/Process (28607): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> I/Process (28607): 	at android.os.Handler.handleCallback(Handler.java:942)
> I/Process (28607): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> I/Process (28607): 	at android.os.Looper.loopOnce(Looper.java:211)
> I/Process (28607): 	at android.os.Looper.loop(Looper.java:300)
> I/Process (28607): 	at android.app.ActivityThread.main(ActivityThread.java:8294)
> I/Process (28607): 	at java.lang.reflect.Method.invoke(Native Method)
> I/Process (28607): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> I/Process (28607): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
> I/Process (28607): Sending signal. PID: 28607 SIG: 9
> Lost connection to device.
> 
> Exited.

Another Android phone crashes with 

> D/libGLESv2(22525): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.bridgefy_test

**Comment by mike-bridgefy** [comment]
Hello, can you _delete/rename_ the main `.gradle` folder and try again?, Flutter manages a lot of cache to work very fast and sometimes you have to clean it. The folder should be in a path like this` /users/{myuser}/.gradle`.
I remain attentive to your results to support you.

**Comment by mike-bridgefy** [comment]
The cache is not of Flutter dependencies but of gradle and since you have run the project before it is possible that it is that, it happened to a member of the team and that is how we solved it.

**Comment by marcotrumpet** [comment]
Hey @mike-bridgefy the trick seems to work. If I can, I'll suggest to add it in a troubleshoting section in the readme file.
I'll add also a section to inform users to add a meta-data into androidmanifest for api key
<meta

> -data
>             android:name="com.bridgefy.sdk.API_KEY"
>             android:value="YOUR_KEY_HERE" />

**Comment by mike-bridgefy** [comment]
Excellent, good that it worked for you!
We are going to add what you mentioned, [we have documentation about it](https://github.com/bridgefy/bridgefy_flutter/tree/main/example) but I think it is a bit hidden, we are going to add the information to the main README.
Thank you very much for your support and we are ready to support you with whatever you need.
